### ISSUE TITLE
CF deep search!

### ISSUE THREAD

**Issue by kamiepic** [scaredos/cfresearch#10]
I am unsure if this is the appropriate place to ask my question, but I am seeking assistance. There are specific IP addresses that belong to a particular company(most of them are cf partners), and when attempting to open them, a Cloudflare error message is displayed. I am interested in determining if it is possible to find the IP addresses that are behind Cloudflare, even if the company is not using Cloudflare's IP ranges. I have attempted to use peers, but some companies have a significant number of IP addresses, making it challenging to identify the IP addresses behind Cloudflare. For instance, the IP address 70.34.214.96 belongs to The Constant Company, but upon opening it, a Cloudflare error message is displayed.
my country blocked all of the Cloudflare IPs and I can't use Cloudflare directly, but I can use these kinds of IP addresses as a meddling man that kind of somehow use Cloudflare, I asked around and I think they are some Cloudflare private ips that Cloudflare use for their partners! i made a script to search some networks that have Cloudflare as peers in them but it's taking years to find anything because of the verrry large amount of IP addresses in the networks
Please let me know if you can provide any insight or assistance, that would help me a lot, thanks

**Comment by scaredos** [comment]
This IP appears to be a reverse proxy. I do not believe them to be secret CloudFlare IP addresses. This is visible through a curl command.
```
curl http://70.34.214.96/cdn-cgi/trace  
fl=83f91
h=constant.com
ip=70.34.214.96
ts=1683392764.43
visit_scheme=http
uag=curl/8.1.0-DEV
colo=OSL
sliver=005-tier2
http=http/1.1
loc=SE
tls=off
sni=off
warp=off
gateway=off
rbi=off
kex=none
```

Then if you view a real request to CloudFlare...

```
curl https://cloudflare.com/cdn-cgi/trace
fl=601f19
h=cloudflare.com
ip=17X.XXX.XXX.XXX
ts=1683392798.39
visit_scheme=https
uag=curl/8.1.0-DEV
colo=IAD
sliver=010-tier1
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519
```
