### ISSUE TITLE
captcha bypass

### ISSUE THREAD

**Issue by andress134** [scaredos/cfresearch#2]
Hello sir @scaredos , do you have experience with scraping, captcha?
Im looking to buy a ddos l7 captcha bypass script, some based public lib like 2captcha, anticaptcha, privacypass
I pay for it, let me know if u can do it, if yes give me your telegram or discod
Thank

**Comment by scaredos** [comment]
My telegram is trespassed

**Comment by andress134** [comment]
> My telegram is trespassed

@scaredos   waiting for your accept, have added and writed yiu  :  my tele : @Nonsess2
