### ISSUE TITLE
Captcha handling

### ISSUE THREAD

**Issue by CedricBrandt** [scaredos/cfresearch#3]
More insight how the captcha parameters are generated would be helpful. 
For example how the captcah_vc and captcha_answer field is produced carrying the hCaptcha response instead of the old h/g-captcha-response fields.
Any idea how one would go examining this?

**Comment by scaredos** [comment]
Contact me on telegram t.me/trespassed


Nov 19, 2020, 4:06 PM by notifications@github.com:
