### ISSUE TITLE
How did you study/debug their scripts?

### ISSUE THREAD

**Issue by doko-desuka** [scaredos/cfresearch#4]
Hi, this is more of a technical question.  
I'm looking at a JS script from `/cdn-cgi/challenge-platform/h/g/orchestrate/jsch/v1`, there's some parts like the following:

```
var t, q, u, v, w, x, y;
for (t = b('0x18'), q = s['dZiYC'](String, q)[b('0x136')](/[\t\n\f\r ]+/g, ''), q += '==' [b('0x16e')](2 - s[b('0x16b')](q[b('0xd3')], 3)), v = '', y = 0; y < q[b('0xd3')]; u = s[b('0x84')](s[b('0x80')](t[b('0x9f')](q[b('0xf6')](y++)), 18), t[b('0x9f')](q[b('0xf6')](y++)) << 12) | (w = t[b('0x9f')](q[b('0xf6')](y++))) << 6 | (x = t['indexOf'](q[b('0xf6')](y++))), v += w === 64 ? String[b('0x5b')](s[b('0x31')](u, 16) & 255) : s[b('0x48')](x, 64) ? String[b('0x5b')](s[b('0x16b')](s[b('0x119')](u, 16), 255), s[b('0x118')](u, 8) & 255) : String[b('0x5b')](u >> 16 & 255, s[b('0x71')](u, 8) & 255, u & 255));
return v
```
That's only a small piece. I think they're using the "pre-rotated list and translation function" (the `b(...)` calls) method that a popular JS obfuscator uses.

How do you usually debug obfuscated JS scripts like that? Once the challenge is solved, it immediately POSTs and redirects the page, so I don't have time to pause the debugger in my Firefox and step in the code.   
Can you give me any tips on how you usually study these systems? (like the tools you use, your process etc.)  
Thank you for your time.

**Comment by scaredos** [comment]
You can start by downloading a browser extension such as "Hookish" that will log each request and response data. Once you view the JS you can insert it into one of many JS Deobfuscators//Debuggers.

**Comment by doko-desuka** [comment]
@scaredos thanks for the reply. I can already view the requests and their data with the Network Monitor (Ctrl+Shift+E) tab of the Dev Console (F12) on Firefox, so I got that covered. It shows request+response headers, request data, response data, timeline etc.

Now, I know no (effective) JS deobfuscators or debuggers, up 'til now I was using the Debugger tab from Firefox.  
The closest thing I guess would be [JSNice](http://www.jsnice.org/), but that only renames some variables and functions (and in this particular case doesn't help that much). Maybe you're talking about offline software?  
Could you name some of the tools that you use?

**Comment by scaredos** [comment]
https://lelinhtinh.github.io/de4js/

**Comment by doko-desuka** [comment]
Interesting, thank you.
