### ISSUE TITLE
A little help with information

### ISSUE THREAD

**Issue by andress134** [scaredos/cfresearch#6]
Hello sir @scaredos , recentry i used cloudscraper (nodejs lib with some changes for bypass hcaptcha, but for 4 days it stopped working)
I dont know what changes he made, i use 2captcha, and lib cloudscraper seems to send data to hcaptcha, but I think the hcaptcha-response is invalid
https://github.com/andress134/cloudscraper/commit/29db1ebe9759b66f2936d4163d8f3f3431bc49b9 here are my changes, i added manualy rayId, sitekey, the response
and until 4 days ago it worked, now it doesn't seem to work, meaning he gets all the data, but they seem invalid
Is it posible if u can to look my changes and help me with some informations what is wrong

**Comment by scaredos** [comment]
Your ray id changes with each request, so making your variable the same each time is not a good idea.

**Comment by andress134** [comment]
> Your ray id changes with each request, so making your variable the same each time is not a good idea.

Hmm, just more one question sir, i think not here problem, im using crypto-random-string to generate random rayid for every request
im looking on new source of hcaptcha and on old
view-source:https://web.archive.org/web/20210327195552/https://captcha.website/ this is old after update
and new source  include this   zh: "hWJ1vBF6YtS8XiMXPDOtBXle1I+k7XXAe+3R44joK+8=",  what is this zh ?
